apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-api.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "task-api.name" . }}
    helm.sh/chart: {{ include "task-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
